version: '3.8'
services:
  maven-sonar:
    image: maven:3.8.6-openjdk-11
    volumes:
      - .:/usr/src/app
      - ~/.m2:/root/.m2
    working_dir: /usr/src/app
    command: >
      mvn -e clean verify sonar:sonar \
      -Dsonar.projectKey=keycloak \
      -Dsonar.projectName='keycloak' \
      -Dsonar.host.url=http://localhost:9000 \
      -Dsonar.token=sqp_931ef157ee314626680d636d7645871dca62df17 \
      -Dinsecure.repositories=WARN \
      -DskipTests \
      > maven-output.log 2>&1
    networks:
      - sonar-net

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    networks:
      - sonar-net

networks:
  sonar-net:
