version: '3.8'
services:
  maven-sonar:
    image: maven:3.8.5-openjdk-17
    volumes:
      - .:/usr/src/app
      - ~/.m2:/root/.m2
    working_dir: /usr/src/app
    network_mode: "host"
    command:
      - /bin/bash
      - -c
      - |
        # Run SonarQube analysis with proper patterns for your specific setup
        mvn -X -e clean verify sonar:sonar \
          -Dsonar.projectKey=keycloak \
          -Dsonar.projectName=keycloak \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.token=sqp_780fa96b6fa9819fb775c59e61618fb84070f10e \
          -Dsonar.inclusions="services/src/main/java/org/keycloak/services/resources/admin/**/*.java,js/apps/admin-ui/**/*.ts,js/apps/admin-ui/**/*.tsx,js/apps/admin-ui/**/*.js,js/apps/admin-ui/**/*.jsx" \
          -Dsonar.exclusions="**/node_modules/**,**/target/**,**/*.test.*,**/*.spec.*,**/test/**,**/tests/**" \
          -Dinsecure.repositories=WARN \
          -DskipTests 2>&1 | tee /usr/src/app/maven-output.log
        echo "Exit code: $?"
        echo "=== LAST 50 LINES OF OUTPUT ==="
        tail -50 /usr/src/app/maven-output.log
